<?php
// $Id$

/**
 * @file
 * Display realtime twitter search.
 */

// TODO: Ability to add unlimited block of search result (profiles).

/**
 * Implementation of hook_menu().
 */
function tweetflow_menu() {
  $items = array();

  $items['admin/settings/tweetflow'] = array(
    'title' => "TweetFlow",
    'description' => "Display twitter search result in realtime.",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tweetflow_settings_form'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Callback function: display settings.
 */
function tweetflow_settings_form() {
  $form = array();

  $form['tweetflow_keyword'] = array(
    '#type' => 'textarea',
    '#description' => t("Enter keyword to search from twitter, seperate by enter (newline)."),
    '#default_value' => variable_get('tweetflow_keyword', ''),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_block().
 */
function tweetflow_block($op = 'list', $delta =0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t("Tweetflow"),
    );

    return $blocks;
  }
  else if ($op == 'configure' && $delta == 0) {
  }
  else if ($op == 'view') {
    $block = array(
      'subject' => t("test"),
      'content' => "Blah",
    );

    return $block;
  }
}

/**
 * Implementation of hook_themes().
 */
function tweetflow_theme($existing, $type, $theme, $path) {
  return array(
    'tweetflow_static' => array(
      'argument' => array('tweets'),
    ),
    'tweetflow_realtime' => array(
      'argument' => array('tweets'),
    ),
  );
}

/**
 * Display realtime search.
 */
function theme_tweetflow_realtime($tweets) {

}
