<?php
// $Id$

/**
 * @file
 * Display realtime twitter search.
 */

// TODO: Ability to add unlimited block of search result (profiles).

define(MODULE_PATH, drupal_get_path('module', 'tweetflow'));

/**
 * Implementation of hook_menu().
 */
function tweetflow_menu() {
  $items = array();

  $items['admin/settings/tweetflow'] = array(
    'title' => "TweetFlow",
    'description' => "Display twitter search result in realtime.",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tweetflow_settings_form'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Callback function: display settings.
 */
function tweetflow_settings_form() {
  $form = array();

  $form['tweetflow_keyword'] = array(
    '#type' => 'textarea',
    '#title' => t('Keyword'),
    '#description' => t("Enter keyword to search from twitter, seperate by enter (newline)."),
    '#default_value' => variable_get('tweetflow_keyword', ''),
  );

  $form['tweetflow_rpp'] = array(
    '#type' => 'textfield',
    '#title' => t('Result per page'),
    '#default_value' => variable_get('tweetflow_rpp', 5),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_block().
 */
function tweetflow_block($op = 'list', $delta =0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t("Tweetflow"),
    );

    return $blocks;
  }
  else if ($op == 'configure' && $delta == 0) {
  }
  else if ($op == 'view') {
    $query = variable_get("tweetflow_keyword", "");
    if (empty($query)) {
      return;
    }
    else {
      $query = explode("\n", $query);
      foreach ($query as $k => &$val) {
        $val = trim($val);
      }
    }

    $rpp = variable_get('tweetflow_rpp', 5);

    $block = array(
      'subject' => t("TweetFlow"),
      'content' => theme('tweetflow_realtime', $query, $rpp),
    );

    return $block;
  }
}

/**
 * Implementation of hook_themes().
 */
function tweetflow_theme($existing, $type, $theme, $path) {
  return array(
    'tweetflow_static' => array(
      'argument' => array('query', 'rpp'),
    ),
    'tweetflow_realtime' => array(
      'argument' => array('query', 'rpp'),
    ),
  );
}

/**
 * Display realtime search.
 */
function theme_tweetflow_realtime($keyword, $rpp) {
  $query = implode('+OR+', $keyword);
  $settings = array(
    'tweetflow_query' => $query,
    'tweetflow_rpp' => $rpp,
    'tweetflow_keyword' => $keyword,
  );

  drupal_add_css(MODULE_PATH .'/tweetflow.css');
  drupal_add_js(MODULE_PATH .'/tweetflow.js');
  drupal_add_js($settings, 'setting');

  $content = '<div class="tweetflow-realtime">Your browser not support javascript.</div>';

  return $content;
}
